### ISSUE TITLE
CFViewController class not found error

### ISSUE THREAD

**Issue by tusharjindal353** [cashfree/ios-CFWebSDK#11]
I have import the CFWebSdk framework in iOS app written in swift 4.2 but it gives compilation error when we create a object of class CFViewController

Error: CFViewController' is unavailable: cannot find Swift declaration for this class
@basilcf @sharroh 
Please help me ASAP.

**Comment by basilcf** [comment]
Hi,
1) Are you running the SDK on a physical iOS Device ?
2) Are you using Xcode 10.1 ?

Please drop an email at techsupport@cashfree.com if you're still facing issues with the integration.

Best Regards,
Basil

**Comment by tusharjindal353** [comment]
@basilcf 
1 I am running the SDK on physical device but it is not compiling
2 I am using Xcode 10.1

**Comment by basilcf** [comment]
In Xcode 10.1 are you using the [Swift 4.2 SDK](https://github.com/cashfree/ios-CFWebSDK/blob/master/CFWebSdk-BitcodeEnabled-Swift4.2.zip) ?

**Comment by tusharjindal353** [comment]
Yes.Using 4.2 SDK

**Comment by basilcf** [comment]
Follow below steps :
1) Delete the Dynamic Framework file from your app.
2) Re add the Dynamic Framework to your project.
3) Delete the import CFWebSdk line from your ViewController.
4) Re add the import CFWebSdk line in your ViewController. (See screenshot, you must see it in code editor autocomplete dropdown)
[![delete-import-line.png](https://i.postimg.cc/d15jtkNM/delete-import-line.png)](https://postimg.cc/7GT2K6yX)

5) Run on Physical device (see screenshot, I just cloned the repo and ran on iPhone 5)
[![running-on-device.png](https://i.postimg.cc/Bn3pp0KV/running-on-device.png)](https://postimg.cc/D8C1fR5r)

**Comment by tusharjindal353** [comment]
I have Performed all these steps but the result are same

**Comment by basilcf** [comment]
Please delete the contents of below folder :
1) /Users/YOUR-USERNAME/Library/Developer/Xcode

If you're still facing the issue, drop an email at techsupport@cashfree.com

**Comment by sharathfantain** [comment]
> Follow below steps :
> 
> 1. Delete the Dynamic Framework file from your app.
> 2. Re add the Dynamic Framework to your project.
> 3. Delete the import CFWebSdk line from your ViewController.
> 4. Re add the import CFWebSdk line in your ViewController. (See screenshot, you must see it in code editor autocomplete dropdown)
>    [![delete-import-line.png](https://camo.githubusercontent.com/5229efded2a85365e8bfae03cb2cede001f7ab17/68747470733a2f2f692e706f7374696d672e63632f6431356a746b4e4d2f64656c6574652d696d706f72742d6c696e652e706e67)](https://postimg.cc/7GT2K6yX)
> 5. Run on Physical device (see screenshot, I just cloned the repo and ran on iPhone 5)
>    [![running-on-device.png](https://camo.githubusercontent.com/47f16d54eb20c2d1367ff5d78fd80ba48a8e8a60/68747470733a2f2f692e706f7374696d672e63632f426e337070304b562f72756e6e696e672d6f6e2d6465766963652e706e67)](https://postimg.cc/D8C1fR5r)

@basilcf Followed your steps given. I am also working on Xcode 10.1, using swift 4.2 sdk, getting "CFWebSdk" in autocomplete. But still I am getting 'CFViewController' is unavailable. Any solution?

**Comment by basilcf** [comment]
@sharathfantain If you're running Xcode 10.1 can you try running the Example app to physical device ? Are you seeing the error in your project or example app?

**Comment by sharathfantain** [comment]
@basilcf 
Xcode - 10.1
App - Our app
And not on physical device, we are trying to run on simulator.

**Comment by basilcf** [comment]
Our SDK only works in Physical device.

**Comment by Komal2905** [comment]
I am trying to run given example and getting same error
I am importing CFSDK .
trying to run on physical device(iPhone 5s).
with Xcode 10.1 (10B61) and swift 4.2
